name: Build and Push Docker Image for Harmony AI's Textgen variant

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-push-amd:
    runs-on: ubuntu-latest

    steps:
      # Frees up additional disk space on GHA runner for building the image
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 30000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-docker-images: 'true'
          remove-android: 'true'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push text-generation-webui-harmony-ai image for AMD
        uses: docker/build-push-action@v3
        with:
          context: ./docker/amd
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/text-generation-webui-harmony-ai-amd:${{ github.ref_name }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/text-generation-webui-harmony-ai-amd:latest

  build-and-push-cpu:
    runs-on: ubuntu-latest

    steps:
      # Frees up additional disk space on GHA runner for building the image
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 30000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-docker-images: 'true'
          remove-android: 'true'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push text-generation-webui-harmony-ai image for CPU
        uses: docker/build-push-action@v3
        with:
          context: ./docker/cpu
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/text-generation-webui-harmony-ai-cpu:${{ github.ref_name }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/text-generation-webui-harmony-ai-cpu:latest

  build-and-push-intel:
    runs-on: ubuntu-latest

    steps:
      # Frees up additional disk space on GHA runner for building the image
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 30000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-docker-images: 'true'
          remove-android: 'true'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push text-generation-webui-harmony-ai image for INTEL
        uses: docker/build-push-action@v3
        with:
          context: ./docker/intel
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/text-generation-webui-harmony-ai-intel:${{ github.ref_name }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/text-generation-webui-harmony-ai-intel:latest

  build-and-push-nvidia:
    runs-on: ubuntu-latest

    steps:
      # Frees up additional disk space on GHA runner for building the image
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 30000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-docker-images: 'true'
          remove-android: 'true'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push text-generation-webui-harmony-ai image for NVIDIA
        uses: docker/build-push-action@v3
        with:
          context: ./docker/nvidia
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/text-generation-webui-harmony-ai-nvidia:${{ github.ref_name }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/text-generation-webui-harmony-ai-nvidia:latest

  build-and-push-tensorrt:
    runs-on: ubuntu-latest

    steps:
      # Frees up additional disk space on GHA runner for building the image
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 30000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-docker-images: 'true'
          remove-android: 'true'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push text-generation-webui-harmony-ai image for TensorRT-LLM
        uses: docker/build-push-action@v3
        with:
          context: ./docker/TensorRT-LLM
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/text-generation-webui-harmony-ai-tensorrt:${{ github.ref_name }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/text-generation-webui-harmony-ai-tensorrt:latest